# Server
server.port=${SERVER_PORT}

# Database
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

# JWT
jwt.base64-secret=${JWT_BASE64_SECRET}
jwt.access-token-validity-in-seconds=${JWT_ACCESS_TOKEN_VALIDITY_IN_SECONDS}
jwt.refresh-token-validity-in-seconds=${JWT_REFRESH_TOKEN_VALIDITY_IN_SECONDS}

# Springdoc
springdoc.swagger-ui.config-url=${SPRINGDOC_SWAGGER_UI_CONFIG_URL}
springdoc.swagger-ui.url=${SPRINGDOC_SWAGGER_UI_URL}
springdoc.api-docs.enabled=${SPRINGDOC_API_DOCS_ENABLED}
springdoc.swagger-ui.enabled=${SPRINGDOC_SWAGGER_UI_ENABLED}

# Swagger / OpenAPI
swagger.server-url=${SWAGGER_SERVER_URL}
swagger.server-desc=${SWAGGER_SERVER_DESC}

# Redis
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.database=${REDIS_DATABASE}
spring.data.redis.timeout=${REDIS_TIMEOUT}

# Static resources & upload
spring.web.resources.static-locations=${SPRING_WEB_RESOURCES_STATIC_LOCATIONS}
app.base-url=${APP_BASE_URL}
app.upload-dir=${APP_UPLOAD_DIR}

# Multipart
spring.servlet.multipart.max-file-size=${MULTIPART_MAX_FILE_SIZE}
spring.servlet.multipart.max-request-size=${MULTIPART_MAX_REQUEST_SIZE}


# Frontend
short-link.base-url=${SHORT_LINK_BASE_URL}

#IpInfo
ipinfo.access-token=${IPINFO_ACCESS_TOKEN}
ipinfo.base-url=${IPINFO_BASE_URL}